// Auto-generated by: npm run db:types
// Regenerate after schema changes: npm run db:types
// This is a placeholder — run db:types after Plans 02 and 03 push schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
